export enum Asset {
    ETH = "ETH",
    WETH = "WETH",
    USDT = "USDT",
    USDC = "USDC",
    MATIC = "MATIC",
    WMATIC = "WMATIC",
    WBTC = "WBTC",
    RETH = "RETH",
    DAI = "DAI",
    LUSD = "LUSD",
    BUSD = "BUSD",
    STETH = "STETH",
    IMX = "IMX",
    SNX = "SNX",
    GRT = "GRT",
    LINK = "LINK",
    AAVE = "AAVE",
    CRV = "CRV",
    UNI = "UNI",
    SUSHI = "SUSHI",
    SHIB = "SHIB",
    LDO = "LDO",
    PEPE = "PEPE",
    DYDX = "DYDX",
    COMP = "COMP",
    WLD = "WLD",
    BLUR = "BLUR",
    ENS = "ENS",
    BAL = "BAL",
    STG = "STG",
    SAND = "SAND",
    FRAX = "FRAX",
    APE = "APE",
    FXS = "FXS",
    ILV = "ILV",
    CVX = "CVX",
    ENJ = "ENJ",

    // === Only zkSync tokens ==
    MUTE = "MUTE",
    IZI = "IZI",
    VC = "VC",
    SIS = "SIS",
    DVF = "DVF",
    MAV = "MAV",
    ZAT = "ZAT",
    ZKDOGE = "ZKDOGE",
    SPACE = "SPACE",
    // =========================


}